import {accountArt} from './account-art.mjs?v=1';
import {uiIcon as accountIcon} from './ui-icons.mjs?v=1';

// Presentation only: callers retain account ownership checks, loading and API work.
// Common context: user, online, esc, fmt, when, brl, avatar, btn, intro, empty, guest.
const paymentLabels={card:'Cartão',pix:'Pix',transfer:'Transferência'};
const depositLabels={pending:'Aguardando confirmação',review:'Comprovante em análise',approved:'Saldo adicionado',rejected:'Recusado',cancelled:'Cancelado'};
const normalizeDeposit=d=>({...d,status:d.status==='confirmed'?'approved':d.status,version:d.version||1});

export function renderWalletView(c){
 const {user,online,esc,fmt,when,brl,btn,intro,empty,guest,wallet:data,legacyDemoView}=c;
 if(!user)return guest('wallet','Sua carteira.','Saldo e movimentações, sempre na sua conta.');
 const pending=online&&Number.isSafeInteger(data.pendingDepositAmount)&&data.pendingDepositAmount>=0?data.pendingDepositAmount:data.deposits.filter(d=>['pending','review'].includes(d.status)&&(!online||d.paymentMode!=='demo')).reduce((n,d)=>n+d.amount,0);
 const realPix=online&&data.paymentMode==='pix_manual'&&data.paymentsAvailable===true&&Array.isArray(data.catalog)&&data.catalog.length>0;
 const unit=!online||data.paymentMode==='demo'?'Joga aí Coin de teste':'Joga aí Coin';
 const rows=data.transactions.map(t=>`<tr><td class='account-date'>${when(t.date||t.createdAt)}</td><td>${esc(t.label)}${t.publicMatchId?`<small class='transaction-reference'>${esc(t.publicMatchId)}</small>`:''}${t.source?`<small>${esc(({reserve:'Reserva',refund:'Devolução',duel_reserve:'Reserva',duel_refund:'Devolução',duel_prize:'Prêmio',duel_settlement:'Prêmio',duel_fee:'Taxa',deposit:'Recarga',admin_adjustment:'Ajuste da equipe'})[t.source]||'Movimentação da conta')}</small>`:''}${Number.isSafeInteger(t.pot)?`<small>Total da partida: ${fmt(t.pot)} · taxa: ${fmt(t.houseFee||0)} Coin</small>`:''}${t.source==='duel_prize'&&Number.isSafeInteger(t.stake)?`<small>Ganho líquido: ${fmt(t.amount-t.stake)} Coin</small>`:''}${Number.isSafeInteger(t.balanceAfter)?`<small>Saldo após: ${fmt(t.balanceAfter)}</small>`:''}</td><td class='account-amount ${t.amount>=0?'credit-positive':''}'>${t.amount>0?'+':''}${fmt(t.amount)} <small>${unit}</small></td></tr>`).join('');
 const deposits=data.deposits.map(raw=>{const d=normalizeDeposit(raw);return `<article class='deposit-row'><div class='grow'><strong>${fmt(d.amount)} ${!online?'Joga aí Coin de teste':d.paymentMode==='demo'?'Joga aí Coin da demonstração antiga':d.paymentMode==='pix_manual'?'Joga aí Coin comprada':'Joga aí Coin'} · ${esc(paymentLabels[d.method]||'Recarga')}${d.priceCents?` · ${brl(d.priceCents)}`:''}</strong><small>${when(d.createdAt)}${d.paymentMode==='demo'?' · Registro antigo de demonstração':''}${!online&&d.method==='card'?` · ${fmt(d.installments)}x de teste`:''}</small>${renderDepositRecovery(d,c)}</div><span class='wallet-status ${esc(d.status)}'>${esc(depositLabels[d.status]||'Aguardando atualização')}</span>${btn('deposit-details',d.id,'Detalhes')}</article>`;}).join('');
 const zero=!data.balance?`${data.reserved?'Seu saldo em Joga aí Coin está reservado em partidas.':'Seu saldo começa em zero.'} ${realPix?'O saldo aumenta depois que a equipe confirma o Pix no banco.':online?'Você pode jogar uma amistosa sem Joga aí Coin.':'Faça uma recarga de teste para conhecer a carteira.'}`:'Prontos para usar nas suas partidas.';
 const purchase=realPix?`<button class='btn primary' data-action='deposit'>Comprar Joga aí Coin via Pix</button>`:online?`<button class='btn secondary' disabled>${accountIcon('lock')}Comprar Joga aí Coin</button>`:`<button class='btn primary' data-action='deposit'>Adicionar Joga aí Coin de teste</button>`;
 const guidance=realPix?`<h2>Joga aí Coin, com conferência.</h2><p>Escolha um pacote Pix. A equipe confirma o recebimento no extrato antes de liberar seu saldo.</p><div class='pix-price-list'>${data.catalog.map(pack=>`<span>${fmt(pack.amount)} Joga aí Coin <strong>${brl(pack.priceCents)}</strong></span>`).join('')}</div><p class='account-note'>O saldo comprado em Joga aí Coin não pode ser sacado. O comprovante não confirma o pagamento por si só.</p>`:online?`<span class='account-status'>Pagamentos em configuração</span><h2>A partida pode começar.</h2><p>Você pode criar uma amistosa sem saldo ou usar Joga aí Coin já disponíveis. A compra continua em configuração.</p><button class='btn primary' data-action='create'>Criar uma amistosa <span aria-hidden='true'>↗</span></button><p class='account-note'>Nenhuma cobrança pode ser iniciada nesta etapa.</p>`:`<h2>Conheça a carteira.</h2><p>Use Joga aí Coin de teste para experimentar reservas e movimentações. Nenhum dinheiro é cobrado.</p><button class='btn secondary' data-action='create'>Criar minha partida <span aria-hidden='true'>↗</span></button><p class='account-note'>Demonstração local, sem valor financeiro.</p>`;
 return `<div class='account-page account-wallet'>${intro('wallet','Seu saldo. Sem mistério.','Acompanhe seu saldo em Joga aí Coin e as reservas de cada partida.')}<div class='wallet-layout'><section class='wallet-main account-surface' aria-label='Resumo da carteira'><span class='wallet-label'>Disponíveis para jogar</span><strong class='account-number'>${fmt(data.balance)} <small>${unit}</small></strong><p class='account-note'>${zero}</p><div class='wallet-balance-split'><div><span>Reservados em partidas</span><strong>${fmt(data.reserved)}</strong><small>${unit}</small></div><div><span>Recargas pendentes</span><strong>${fmt(pending)}</strong><small>${unit}</small></div></div><div class='account-actions'>${purchase}</div></section><aside class='wallet-guidance' aria-label='Como começar'>${accountArt('wallet')}${guidance}</aside></div>${online?legacyDemoView(data):''}<section class='account-section'><div class='account-section-head'><h2>Minhas recargas</h2><button class='text-button' data-action='refresh'>Atualizar</button></div>${deposits||empty('wallet','Nenhuma recarga por aqui.',realPix?'Suas compras e o andamento da conferência aparecem aqui.':online?'Quando a compra estiver disponível, você poderá acompanhar os pedidos aqui.':'As recargas de teste que você fizer aparecem aqui.')}</section>${data.depositsNextCursor?`<button class='btn secondary' data-action='wallet-more-deposits'>Carregar mais recargas</button>`:''}<section class='account-section'><div class='account-section-head'><h2>Extrato</h2><p>Últimas movimentações</p></div>${rows?`<div class='account-table-wrap'><table class='account-table'><thead><tr><th scope='col'>Data</th><th scope='col'>Movimentação</th><th scope='col' class='account-amount'>Joga aí Coin</th></tr></thead><tbody>${rows}</tbody></table></div>`:empty('history','Seu extrato começa aqui.','Recargas confirmadas, reservas e resultados das partidas ficam registrados nesta área.')}${data.transactionsNextCursor?`<button class='btn secondary' data-action='wallet-more-transactions'>Carregar mais movimentações</button>`:''}</section></div>`;
}

export function renderHistoryView(c){
 const {user,esc,fmt,when,avatar,btn,intro,empty,guest,duels:all,opponent,matchCode,playerScore,resultText,duelUnit,tones}=c;
 if(!user)return guest('history','Histórico das partidas.','Cada confronto, do convite ao apito final.');
 const search=c.search||'',filter=c.filter||'all',query=search.trim().toLocaleLowerCase('pt-BR');
 const list=all.filter(d=>{const other=opponent(d);return (!query||`${other?.nickname||''} ${other?.publicPlayerId||''} ${matchCode(d)} ${d.mode}`.toLocaleLowerCase('pt-BR').includes(query))&&(filter==='all'||(filter==='review'?['review','disputed'].includes(d.status):filter==='cancelled'?['cancelled','rejected','expired'].includes(d.status):d.status===filter));});
 const filtered=!!query||filter!=='all';
 const rows=list.map(d=>{const other=opponent(d),date=new Date(d.createdAt),valid=!Number.isNaN(date.valueOf());return `<article class='match-history-row'><time class='history-date' datetime='${esc(d.createdAt)}' aria-label='${esc(when(d.createdAt))}'><strong>${valid?date.toLocaleDateString('pt-BR',{day:'2-digit'}):'—'}</strong><span>${valid?date.toLocaleDateString('pt-BR',{month:'short'}).replace('.','').toUpperCase():''}</span></time>${avatar(other)}<div class='history-rival'><h2>Você × ${esc(other?.nickname||'Amigo convidado')}</h2><p>${esc(matchCode(d)||'Convite pendente')} · ${esc(d.mode)}</p><small>${d.stake?`${fmt(d.stake)} ${esc(duelUnit(d))} por jogador`:'Amistosa · sem Joga aí Coin'}</small></div><span class='history-score' aria-label='Placar: você ${esc(playerScore(d))} rival'>${playerScore(d)}</span><span class='pill ${esc(tones[d.status]||'subtle')}'>${esc(resultText(d))}</span>${btn('details',d.id,'Detalhes')}</article>`;}).join('');
 return `<div class='account-page account-history'>${intro('history','Seu jogo tem história.','Cada confronto, do convite ao apito final.')}<div class='history-filters'><label for='historySearch'><span class='form-label'>Buscar rival ou ID da partida</span><input class='form-input' type='search' id='historySearch' value='${esc(search)}' placeholder='Apelido, ID do jogador ou código da partida'></label><label for='historyStatus'><span class='form-label'>Situação</span><select id='historyStatus' class='form-input'>${[['all','Todas as partidas'],['settled','Finalizadas'],['review','Em análise'],['cancelled','Canceladas / recusadas']].map(([v,label])=>`<option value='${v}' ${filter===v?'selected':''}>${label}</option>`).join('')}</select></label></div><div class='account-list-note'><span>${list.length} ${list.length===1?'partida':'partidas'}${filtered?(list.length===1?' encontrada':' encontradas'):''}</span>${filtered?`<button class='text-button' data-action='clear-history'>Limpar filtros</button>`:''}</div>${rows?`<section class='account-surface history-match-list' aria-label='Partidas da sua conta'>${rows}</section>`:filtered?empty('history','Nenhuma partida com esses filtros.','Tente outro apelido ou código, ou limpe os filtros para ver todos os confrontos.',`<button class='btn secondary' data-action='clear-history'>Ver todas as partidas</button>`):empty('history','Seu primeiro clássico está por vir.','Crie uma partida e chame um amigo. O convite e o resultado aparecerão aqui.',`<button class='btn primary' data-action='create'>Criar minha partida</button>`)}${c.nextCursor?`<button class='btn secondary' data-action='history-more'>Carregar mais partidas</button>`:''}<aside class='account-quiet-note'>${accountIcon('history')}<div><h2>O placar entra depois da revisão.</h2><p>Fotos e informações da disputa ficam disponíveis somente às pessoas autorizadas.</p></div></aside></div>`;
}

export function renderRankingView(c){
 const {user,esc,fmt,avatar,intro,empty,guest,entries:items=[],ownId,local=false}=c;
 if(!user)return guest('ranking','Ranking dos jogadores.','Entre para acompanhar os resultados revisados.');
 const personal=c.personal,personalSummary=personal?`<section class='account-surface ranking-personal'><h2>Sua posição</h2><p><strong>${personal.rank&&!personal.unranked?`${fmt(personal.rank)}º`:'Ainda sem partidas classificadas'}</strong> · Pontuação de habilidade (Elo): ${fmt(personal.rating??1000)} · ${fmt(personal.points??0)} pontos</p><p class='account-note'>${fmt(personal.played??0)} jogos classificados · ${fmt(personal.wins??0)} vitórias</p><p class='account-note'>A pontuação Elo muda conforme o resultado validado e a habilidade do rival. Pontos por vitória e empate são contados separadamente.</p>${renderRankingEvolution(c)}</section>`:'';
 const rows=items.map((e,i)=>{const own=e.player.publicPlayerId===ownId;return `<tr ${own?`class='ranking-own'`:''}><td class='ranking-position'>${e.rank||i+1}</td><th scope='row'><div class='ranking-player'>${avatar(e.player)}<div><strong>${esc(e.player.nickname)}${own?`<span class='ranking-you'>você</span>`:''}</strong><small>${esc(e.player.publicPlayerId)}</small></div></div></th>${c.policy?`<td>${fmt(e.rating??1000)}</td><td>${fmt(e.points??0)}</td>`:''}<td>${fmt(e.played)}</td><td>${fmt(e.wins)}</td><td>${fmt(e.draws)}</td><td>${fmt(e.losses)}</td></tr>`;}).join('');
 return `<div class='account-page account-ranking'>${intro('ranking','Faça seu nome.',local?'Classificação dos perfis deste navegador, com resultados de teste.':'A classificação considera partidas com resultado validado.')}<p class='ranking-note'>${accountIcon('ranking')}<span>${local?'Demonstração local · sem valor financeiro.':'Classificação por resultados validados.'}</span></p>${personalSummary}${!local&&c.policy?`<p class='account-note'>Até ${fmt(c.policy.pairDailyLimit??c.policy.maxPairResultsPerUtcDay??c.policy.maxPairMatchesPerDay??3)} confrontos do mesmo par por dia (UTC) contam na classificação. Os demais continuam no histórico e mantêm a premiação.</p>`:''}${rows?`<section class='account-surface ranking-panel'><div class='account-section-head'><h2>Classificação</h2><span class='account-note'>${items.length} ${items.length===1?'jogador':'jogadores'}</span></div><div class='account-table-wrap'><table class='account-table ranking-table'><thead><tr><th scope='col'>Pos.</th><th scope='col'>Jogador</th>${c.policy?`<th scope='col'>Pontuação de habilidade (Elo)</th><th scope='col'>Pontos</th>`:''}<th scope='col'><abbr title='Jogos'>J</abbr></th><th scope='col'><abbr title='Vitórias'>V</abbr></th><th scope='col'><abbr title='Empates'>E</abbr></th><th scope='col'><abbr title='Derrotas'>D</abbr></th></tr></thead><tbody>${rows}</tbody></table></div><p class='ranking-key'>J: jogos · V: vitórias · E: empates · D: derrotas</p></section>`:empty('ranking','A primeira vitória ainda está em jogo.','Partidas em análise ficam no histórico. A classificação começa com resultados revisados.',`<button class='btn primary' data-action='create'>Criar minha partida</button><a class='text-button' href='#historico'>Ver meu histórico</a>`)}<aside class='account-quiet-note'>${accountIcon('ranking')}<div><h2>Jogue. Envie o placar. Confirme com o rival.</h2><p>Os dois jogadores enviam a foto e confirmam o placar. Divergências e leituras inconclusivas seguem para a equipe.</p></div><button class='btn secondary' data-action='create'>Criar partida</button></aside></div>`;
}

export function renderProfileView(c){
 const {user:p,online,esc,avatar,intro,guest,club,country}=c;
 if(!p)return guest('profile','Meu perfil.','Seu apelido, seu time e sua identidade na arena.');
 // The accent comes only from the fixed club catalog; no arbitrary CSS input.
 const clubColor=/^#[\da-f]{6}$/i.test(club?.colors?.[0]||'')?club.colors[0]:'#73e8a7';
 return `<div class='account-page account-profile'>${intro('profile','Seu jeito de entrar em campo.','A camisa, o apelido e o ID que seus amigos reconhecem.')}<div class='profile-layout'><section class='account-surface profile-identity' style='--club-color:${clubColor}' aria-label='Seu perfil'><span class='profile-kicker'>Seu perfil</span><div class='profile-jersey'>${avatar(p,'large')}</div><h2>${esc(p.nickname)}</h2><p>${country?`${esc(country)} · `:''}${esc(club?.name||'Escolha seu time do coração')}</p><div class='profile-id-value'><span>ID de jogador</span><code>${esc(p.publicPlayerId)}</code><button class='btn secondary' data-action='copy-id'>Copiar meu ID</button></div></section><div class='profile-information'><section class='account-surface'><div class='account-section-head'><h2>Identidade de jogo</h2><button class='text-button' data-action='profile'>Editar perfil</button></div><dl class='profile-facts'><div><dt>Apelido</dt><dd>${esc(p.nickname)}</dd></div>${country?`<div><dt>País de residência</dt><dd>${esc(country)}</dd></div>`:''}<div><dt>Time do coração</dt><dd>${esc(club?.name||'Não selecionado')}</dd></div><div><dt>ID Fifa GO</dt><dd>${esc(p.publicPlayerId)}</dd></div>${[['eaId','ID EA'],['psnId','ID PlayStation'],['xboxId','ID Xbox'],['gameEdition','Edição do jogo'],['consoleGeneration','Geração do console'],['crossplay','Crossplay']].filter(([key])=>p.gameAccount?.[key]).map(([key,label])=>`<div><dt>${label}</dt><dd>${esc(key==='crossplay'?({any:'A combinar',enabled:'Ativado',disabled:'Desativado'})[p.gameAccount[key]]:p.gameAccount[key])}</dd></div>`).join('')}</dl><p class='account-note'>Identidades de jogo declaradas por você. Não há conexão automática com EA, PlayStation ou Xbox.</p><p class='account-note'>Envie seu ID ao amigo para ele encontrar você. O Fifa GO não consulta automaticamente o histórico do EA SPORTS FC.</p><div class='account-actions'><button class='btn primary' data-action='create'>Chamar um amigo</button><a class='text-button' href='#historico'>Ver meu histórico</a></div></section><section class='account-surface profile-session'><h2>Conta e privacidade</h2><p>${online?'Seu saldo, e-mail e evidências ficam fora dos convites públicos.':'Demonstração local. Seu perfil e sua coleção ficam neste navegador.'}</p><div class='account-actions'><a class='btn secondary' href='legal.html#privacidade' target='_blank' rel='noopener'>Privacidade</a><button class='text-button' data-action='login'>${online?'Trocar conta':'Trocar perfil'}</button><button class='text-button' data-action='logout'>Sair da conta</button></div></section>${online?renderProfileTools(c)+renderAccountAchievements(c):''}${!online?`<section class='account-surface'><h2>Sua coleção</h2><p class='account-note'>Sua coleção anterior foi preservada neste navegador.</p><div class='account-actions'><a class='btn secondary' href='colecao.html#loja'>Coleção e personalização</a></div></section>`:''}</div></div></div>`;
}

function renderRankingEvolution(c){
 const recent=Array.isArray(c.personal?.recent)?c.personal.recent.slice(0,10):[];
 if(!recent.length)return '';
 const {esc,fmt,when=value=>value}=c,labels={win:'Vitória',draw:'Empate',loss:'Derrota'};
 return `<section class='ranking-evolution' aria-label='Evolução da pontuação de habilidade'><h3>Evolução das partidas classificadas</h3><div class='account-table-wrap'><table class='account-table'><thead><tr><th scope='col'>Partida</th><th scope='col'>Resultado</th><th scope='col'>Variação Elo</th><th scope='col'>Elo após a partida</th></tr></thead><tbody>${recent.map(entry=>`<tr><th scope='row'>${esc(entry.publicMatchId||'Partida validada')}${entry.approvedAt?`<small>${esc(when(entry.approvedAt))}</small>`:''}</th><td>${labels[entry.outcome]||'Resultado validado'}</td><td>${Number.isFinite(entry.change)?`${entry.change>0?'+':''}${esc(fmt(entry.change))}`:'—'}</td><td>${Number.isFinite(entry.rating)?esc(fmt(entry.rating)):'—'}</td></tr>`).join('')}</tbody></table></div></section>`;
}

function renderProfileTools(c){
 const permission=c.notifications?.permission;
 const notice=c.notifications?.supported===false?'Este navegador não oferece avisos. Você pode acompanhar as novidades na arena.':permission==='denied'?'Os avisos estão bloqueados nas configurações do navegador.':c.notifications?.enabled===true?'Avisos ativados neste navegador enquanto o app estiver aberto.':'Os avisos são opcionais e precisam da sua permissão. Funcionam enquanto o app estiver aberto.';
 return `<section class='account-surface profile-security'><h2>Segurança da conta</h2><p class='account-note'>Confira suas sessões, encerre acessos e cuide da recuperação da conta. Os códigos de recuperação são pessoais.</p><div class='account-actions'><button class='btn secondary' data-action='security'>Sessões e recuperação</button></div></section><section class='account-surface profile-notifications'><h2>Avisos da arena</h2><p class='account-note'>${notice}</p><div class='account-actions'><button class='btn secondary' data-action='notifications'>${c.notifications?.enabled===true?'Gerenciar avisos':'Configurar avisos'}</button></div></section><section class='account-surface profile-retention'><h2>Seus dados</h2><p class='account-note'>Você pode pedir a exclusão da conta. Disputas pendentes e registros financeiros precisam ser preservados durante a análise.</p><div class='account-actions'><button class='text-button' data-action='delete-account'>Solicitar exclusão da conta</button></div></section>`;
}

// Original geometric achievement mark; no licensed cards or purchased rewards.
const achievementIcon=`<svg class='achievement-icon' viewBox='0 0 32 32' fill='none' stroke='currentColor' stroke-width='1.6' stroke-linecap='round' stroke-linejoin='round' aria-hidden='true' focusable='false'><circle cx='16' cy='12' r='8'/><path d='m12 19-2 10 6-3 6 3-2-10M12 12l3 3 5-6'/></svg>`;
export function renderAccountAchievements(c){
 if(!c.user||!c.online)return '';
 const {esc,when=value=>value}=c,items=Array.isArray(c.achievements)?c.achievements:[];
 return `<section class='account-surface profile-achievements'><h2>Conquistas das partidas</h2><p class='account-note'>Conquistas da sua conta, a partir de resultados validados.</p>${items.length?`<ul class='account-achievements'>${items.map(item=>`<li>${achievementIcon}<div><h3>${esc(item.title||item.name||'Conquista validada')}</h3>${item.description?`<p>${esc(item.description)}</p>`:''}${item.earnedAt?`<small>Conquistada em ${esc(when(item.earnedAt))}</small>`:''}</div></li>`).join('')}</ul>`:`<p class='account-note'>Suas conquistas aparecem aqui conforme as partidas são validadas.</p>`}</section>`;
}

function renderDepositRecovery(deposit,{online,esc,when}){
 if(!online||deposit.paymentMode!=='pix_manual')return '';
 const recovery=deposit.recovery;
 const label=recovery?.outcome==='credit'&&deposit.status==='approved'?'Saldo recuperado após conferência da equipe.':recovery?.outcome==='refund_recorded'&&['cancelled','rejected'].includes(deposit.status)?'Devolução registrada pela equipe. Nenhum saldo adicionado.':null;
 if(!label)return '';
 const date=recovery.date||recovery.recordedAt;
 return `<small class='deposit-recovery-note'>${label}${date?` · ${esc(when(date))}`:''}</small>`;
}
