// Presentation only: account, wallet and match state are supplied by play.js.
export function renderLobbyView({user,online,friendly,unit,hint,reserved,joinForm,queue,activitySummary={},esc,fmt,icon}) {
  const footnote=online?'Amistosa sem Coin ou sala com Joga aí Coin':'Demonstração local · Coin fictícios';
  const sessionNote=online?'':'<div class="local-demo-note"><span><strong>Demonstração neste navegador.</strong> Convites entre aparelhos precisam da versão conectada.</span><button class="text-button" data-action="connection">Entenda</button></div>';
  const generatedNickname=user&&/^Jogador_[a-f0-9]{8}$/i.test(user.nickname);
  const identity=user?`<div class="taste-home-title home-player-bar"><div class="home-player-greeting">${generatedNickname?'<span>Deixe seu perfil com a sua cara.</span><button class="text-button" data-action="profile">Escolha seu apelido</button>':`<span>Joga aí, <strong>${esc(user.nickname)}</strong>.</span>`}</div><div class="home-player-id"><span>Seu ID</span><code>${esc(user.publicPlayerId)}</code><button class="text-button" data-action="copy-id" aria-label="Copiar meu ID de jogador">${icon('copy')} Copiar</button></div></div>`:'<div class="taste-home-title"><p>Entre amigos. Dentro do jogo.</p></div>';
  const count=key=>Number.isSafeInteger(activitySummary[key])&&activitySummary[key]>0?activitySummary[key]:0;
  const incoming=count('incoming'),active=count('active');
  const activity=user&&(incoming||active)?`<section class="home-activity-shortcuts" aria-label="Suas próximas partidas"><span>Na sua arena</span><div>${incoming?`<button class="text-button" data-action="view-activity" data-id="incoming">${icon('users')}<strong>${fmt(incoming)} ${incoming===1?'convite recebido':'convites recebidos'}</strong>${icon('chevron')}</button>`:''}${active?`<button class="text-button" data-action="view-activity" data-id="active">${icon('ball')}<strong>${fmt(active)} ${active===1?'partida em andamento':'partidas em andamento'}</strong>${icon('chevron')}</button>`:''}</div></section>`:'';
  const balance=user?`<section class="taste-wallet-inline" aria-label="Resumo da carteira"><div>${icon('wallet')}<div><strong>${fmt(user.balance)} ${esc(unit)} disponíveis</strong><small>${fmt(reserved)} reservados em partidas</small><p>${esc(hint)}</p></div></div><a class="text-button" href="#carteira">Ver minha carteira ${icon('arrow')}</a></section>`:`<section class="taste-onboard-inline">${icon('profile')}<div><h2>Um ID só seu. Uma arena para seus amigos.</h2><p>${online?'Crie seu perfil para convidar, jogar e acompanhar suas partidas.':'Crie um perfil local para experimentar. Sua conta começa com saldo zero.'}</p></div><button class="btn secondary" data-action="signup">${online?'Conhecer meu perfil':'Criar perfil local'}</button></section>`;
  return identity+sessionNote+
    `<section class="taste-home-hero" aria-labelledby="createTitle"><picture><source media="(max-width: 820px)" srcset="assets/brand/lobby-footballer-mobile-v2.webp" type="image/webp"><source srcset="assets/brand/lobby-footballer-desktop-v2.webp" type="image/webp"><img src="assets/brand/lobby-footballer-v1.png" alt="Ilustração original de jogador em movimento com uma bola em um estádio" width="1942" height="809" fetchpriority="high" decoding="async"></picture><div class="taste-hero-copy"><h1 id="createTitle">O próximo clássico<br>começa com <em>você.</em></h1><p>Chame um amigo. Combine as regras.<br>Resolva dentro de campo.</p><div class="taste-hero-actions"><button class="btn primary" data-action="create">Criar minha partida ${icon('arrow')}</button><a class="text-button" href="#salas">Ver salas na arena ${icon('arrow')}</a><span class="taste-hero-foot">${icon('ball')}${esc(footnote)}</span></div></div></section>`+
    activity+
    `<section class="taste-invite-strip" aria-labelledby="joinTitle"><div>${icon('copy')}<div><h2 id="joinTitle">Já tem um convite?</h2><p>Confira o desafio antes de aceitar.</p></div></div>${joinForm}</section>`+
    (user?queue:'')+balance+'<div id="installApp"></div>';
}
