// Approved Taste presentation. All account and match data come from play.js.
export function renderLobbyView({user,online,friendly,unit,hint,reserved,joinForm,queue,esc,fmt,icon}){
 const footnote=online?(friendly?'Amistosa · sem créditos':'Créditos reservados somente após sua confirmação'):'Demonstração local · créditos fictícios';
 const sessionNote=online?'':'<div class="local-demo-note"><span><strong>Demonstração neste navegador.</strong> Convites entre aparelhos precisam da versão conectada.</span><button class="text-button" data-action="connection">Entenda</button></div>';
 const balance=user?'<section class="taste-wallet-inline" aria-label="Resumo da carteira"><div>'+icon('wallet')+'<div><strong>'+fmt(user.balance)+' '+esc(unit)+' disponíveis</strong><small>'+fmt(reserved)+' reservados em partidas</small><p>'+esc(hint)+'</p></div></div><a class="text-button" href="#carteira">Ver minha carteira '+icon('arrow')+'</a></section>':'<section class="taste-onboard-inline">'+icon('profile')+'<div><h2>Um ID só seu. Uma arena para seus amigos.</h2><p>'+ (online?'Crie seu perfil para convidar, jogar e acompanhar suas partidas.':'Crie um perfil local para experimentar. Sua conta começa com saldo zero.')+'</p></div><button class="btn secondary" data-action="signup">'+(online?'Conhecer meu perfil':'Criar perfil local')+'</button></section>';
 return '<div class="taste-home-title"><p>Entre amigos. Dentro do jogo.</p><span>EA SPORTS FC · jogo compatível</span></div>'+sessionNote+
 '<section class="taste-home-hero" aria-labelledby="createTitle"><img src="assets/brand/lobby-footballer-v1.png" alt="Ilustração original de jogador em movimento com uma bola em um estádio" width="1942" height="809" fetchpriority="high"><div class="taste-hero-copy"><p class="eyebrow">A sua arena</p><h1 id="createTitle">O próximo clássico<br>começa com <em>você.</em></h1><p>Chame um amigo. Combine as regras.<br>Resolva dentro de campo.</p><div class="taste-hero-actions"><button class="btn primary" data-action="create">Criar minha partida '+icon('arrow')+'</button><button class="text-button" data-action="help">Como funciona</button></div><div class="taste-hero-foot">'+icon('ball')+'<span>'+esc(footnote)+'</span></div></div><span class="taste-hero-edition">01 / Joga aí</span></section>'+
 '<section class="taste-invite-strip" aria-labelledby="joinTitle"><div>'+icon('copy')+'<div><h2 id="joinTitle">Já tem um convite?</h2><p>Confira o desafio antes de aceitar.</p></div></div>'+joinForm+'</section>'+
 (user?queue:'')+balance+'<div id="installApp"></div>'+
 (user?'<div class="lobby-meta"><span>Seu ID <code>'+esc(user.publicPlayerId)+'</code> <button class="text-button" data-action="copy-id">'+icon('copy')+' Copiar</button></span><span>'+ (online?'Conta conectada':'Perfil neste navegador')+'</span></div>':'');
}
